#!/usr/bin/env node

const esmImport = require('esm')(module)
const run = esmImport('./bigRunner.js').default

const str = process.argv[2] || 'hello'
let mmodelParams = process.argv[3] || ''
mmodelParams = new Function(`return {${mmodelParams}}`)()

const className = str.charAt(0).toUpperCase() + str.slice(1) + 'Model'

console.log('Running', className, 'in node')

const params = {
    classPath: `../models/${className}.js`,
    className: className,
    steps: 500,
    seed: true,
}
Object.assign(params, mmodelParams)
// console.log(params, mmodelParams, run)

run(params)
