name: GitHub Pages

on:
    push:
        branches:
            - master # Deploy whenever the master branch is updated

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Checkout the repository code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Create .nojekyll to disable Jekyll processing
            - name: Create .nojekyll
              run: touch .nojekyll

            # Step 3: Upload files to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: actions/configure-pages@v3

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1
