on:
    push:
        branches:
            - master

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create .nojekyll
              run: touch .nojekyll

            - name: Install dependencies
              run: npm install

            - name: Build site
              run: npm run build-dist

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1
